spring:
  #激活哪一个环境的配置文件
  profiles: dev
  #连接池配置
  datasource:
    # 数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowMultiQueries=true
    username: root
    password: root
  #redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空
    password:
    # 连接超时时间
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 8
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1

#日志
logging:
  config: classpath:log/logback.xml
  path: log
  level:
       pers.luchuan.test.dao: debug
